### ISSUE TITLE
Create an epic for What new projects need to do

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin-new-project-provisioning#1]
### Overview
We need to define what new projects need (checklist) and how to do each of the steps, so that new admin members can setup a project.

### Action Items
- [ ] Revise this issue action items to reflect the items from workflow modeling
- [ ] Record doing each of the [actions](https://github.com/hackforla/admin-new-project-provisioning/issues/1#issuecomment-1450587210)
- [ ] Turn recordings into wiki pages
- [ ] Create issue template for starting up a new project

### Resources/Instructions
- [Workflow modeling issue template](https://github.com/hackforla/admin/issues/new?assignees=&labels=0.1-Status%3A+Setup+Epic&template=epic-for-workflow-modeling.md&title=Workflow+Modeling%3A+%5Bname+of+technology%5D)
- https://squidfunk.github.io/mkdocs-material/

**Comment by ExperimentsInHonesty** [comment]
## New Project Provisions: Google Site Playground
currently here https://github.com/hackforla/admin/wiki/New-Project-Provisioning
- What kind of project is it?
  - for a hack for LA project
  - for a digital public good
     - if its a dpg it goes to CTS github org
- GitHub Repo 📹 ✅
  - gather details
     - name: google-site-playground
     - description: houses all the information on how to set up a customizable Google site with tutorials on how to use it
     - template to use if its a HfLA project: https://github.com/hackforla/.github-hackforla-base-repo-template
     - template to use if its a DPG:  https://github.com/hackforla/.github-hackforla-base-repo-template
   - setup teams 📹 ✅
     - add people to teams (check for wiki guidance)
     - make leads able to add new team members (check for wiki guidance)
  - Remove unnecessary issue templates 
    - describe each template purpose 📹
    - removing the templates for the repo 📹 ✅
  - Project Board 📹
  - Wiki 📹
- Google Shared Drive 📹
  - make from the hfla-email-all account
- One Sheet 📹
  - first draft
- 1password vault (link to existing guide)
- Gmail account 📹
  - 2FA Setup (link to existing guide)
- Slack Channel 📹 or find slack tutorial online
- Figma Account 📹
  - make from the project email account
- Branding  
  - Brand Book 📹
- Project Page on hackforla.org
  - gather assets
  - opening a ticket on the website team repo 📹
- Social Media Accounts
  - 📹

**Comment by Rabia2219** [comment]
# Issue Template Details

Issue name:
Labels:

------


### Overview
We need to define what new projects need (checklist) and how to do each of the steps, so that new admin members can setup a project.

### Action Items
#### GitHub Repo Setup
- [ ] gather details
   - [ ] name
   - [ ] description
   - [ ] template to use
- [ ] Teams
- [ ] Remove unnecessary issue templates
- [ ] Project Board
- [ ] Wiki
- [ ] Labels
- [ ] Milestones

#### Create Project Vision
- [ ] draft a project One Sheet

#### 1password Setup
- [ ] create a project vault

#### Google Assets
- [ ] Shared drive
- [ ] Gmail account

#### Security Setup
- [ ] create login account in 1password
- [ ] add 2FA to login account in 1password

#### Create Initial Branding Assets
- [ ] Logo

#### Create Project Assets
- [ ] Team roster
- [ ] hackforla.org page

#### Create Project Templates
- [ ] Form Template
- [ ] Spreadsheet Template
- [ ] Document Template
   - [ ] email
   - [ ] report
   - [ ] letter

#### Create External Assets
- [ ] Slack Channel
- [ ] Figma Account

#### Create Social Media Accounts
- [ ] Twitter
- [ ] Instagram
- [ ] TikTok
- [ ] Facebook
